event_event_proposition:
    resource: "@EventBundle/Controller/EventPropositionController.php"
    type:     annotation

event_activity_event:
    resource: "@EventBundle/Controller/ActivityEventController.php"
    type:     annotation

shop_purchase:
    resource: "@ShopBundle/Controller/PurchaseController.php"
    type:     annotation

shop_product:
    resource: "@ShopBundle/Controller/ProductController.php"
    type:     annotation

pages_page:
    resource: "@PagesBundle/Controller/PageController.php"
    type:     annotation

gallery_picture:
    resource: "@GalleryBundle/Controller/PictureController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

gallery:
    resource: "@GalleryBundle/Controller/"
    type:     annotation
    prefix:   /gallery/

shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /shop/

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /events/

pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /pages/

index:
    resource: "@IndexBundle/Controller/"
    type:     annotation
    prefix:   /
