user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

gallery:
    resource: "@GalleryBundle/Controller/"
    type:     annotation
    prefix:   /gallery/

shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /shop/

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /events/

pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /pages/

index:
    resource: "@IndexBundle/Controller/"
    type:     annotation
    prefix:   /
